import type { Metadata } from "next";
import { Gilda_Display, Barlow } from "next/font/google";
import "./styles/globals.scss";
import "./styles/nav&button.scss";
import { Footer, Navbar } from "@/components";

const geistSans = Gilda_Display({
  variable: "--font-geist-sans",
  weight: ["400"],
  subsets: ["latin"],
});

const barlow = Barlow({
  variable: "--font-barlow",
  weight: ["400", "600", "700"],
  subsets: ["latin"],
});

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: Readonly<{
  children: React.ReactNode;
}>) {
  return (
    <html lang="en">
      <body
        suppressHydrationWarning={true}
        className={`${geistSans.variable} ${barlow.variable} antialiased`}
      >
        <Navbar />
        {children}
        <Footer />
      </body>
    </html>
  );
}
